name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install --frozen-lockfile

      - run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_Tnxnn4qanH4n2zmoqxuPNxDN
          VERCEL_PROJECT_ID: prj_ejzbe13GUMQYiEnyFRyPh9n2Zepz

      - run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_Tnxnn4qanH4n2zmoqxuPNxDN
          VERCEL_PROJECT_ID: prj_ejzbe13GUMQYiEnyFRyPh9n2Zepz

      - run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_Tnxnn4qanH4n2zmoqxuPNxDN
          VERCEL_PROJECT_ID: prj_ejzbe13GUMQYiEnyFRyPh9n2Zepz
